### ISSUE TITLE
Conda recipe tests fails despite succeeding

### ISSUE THREAD

**Issue by jchodera** [choderalab/ambermini#18] opened 2015-07-07 12:54 UTC
See https://github.com/omnia-md/conda-recipes/issues/249#issuecomment-119165669

**Comment by swails** [comment] 2015-07-07 13:00
Closing duplicate of #17

**Closed by swails** 2015-07-07 13:00 UTC

**Comment by jchodera** [comment] 2015-07-07 13:07
Whoops, sorry. Was submitting from phone.
